dist: xenial
language: python
sudo: required

python:
 - 3.6
 - 3.7

services:
 - docker

install:
  - pip install --upgrade pip setuptools
  - pip install -r requirements-dev.txt
  - pip --version

script:
- pytest

cache: pip

jobs:
  include:
    - &deploy_job
      stage: deploy
      name: Publishing if tag is present
      env: PYPI_UPLOAD = true
      if: tag IS present
      install: []
      script: skip

      before_deploy:
        - pip install --upgrade pep517
        - python -m pep517.build --source --binary --out-dir dist .
        - echo > setup.py

      deploy: &deploy_step
        provider: pypi
        server: https://test.pypi.org/legacy/
        skip-cleanup: true
        skip_existing: true
        user: j5ew9
        password:
              secure: LqzRr1yqCNSx5NmTftezvwr1PqiwEpBOJSNL/RVJp7vBwbvp2gGgRDvgXtPv2U8haH/cbChQ4XoqYQHuzngAdUFIzvLQCvMZowRnAMG3y/rdUP22tDkZe33OkGYFeZ/OGuO180KgmqCjw7xvIpTEtaPposNs6Z5tNCdAQR+k1EnXzH9Fs5vEyKYHDeKc+vjuUvuWfsJBuCdwFO2Yoq/eJsaMLHAUE9cfzfBeRCUUSP8CM9DL/orWm6mK6hi9KHfpI3i87+sK7kp5o2Vqc0pGllOqzfAnI8iQ/3Q7nObdnePNSko7Yx9CgZ4t0cSz8sMHs0ksi5k0r6BvcfQp3oyVtJFXYg/0ta2DRSJwH8cnOdMBTK4x2R0m56/yUPPhQqdNSDMrlVQRX7gbXYMtiBZk8UlsGVvscBKaaoHbSjmCkBNERtUBXjl1pvcLKHV6PLbQf/oH0oIvM+A0zkAMR3FNvvIZ9rKQbDd8G8IF+iWWEJQ3/AAZHWc2kM9VakGanUBaHYmdkNgAJmvCqFbfcKFT1ibysLnU2Yy0FZwicd0uFgoP7Ie2A8nEZ1vItCOZw+ZNi0hmAWwHa1LUzVH1BFjQe/jaDi5WjPd9ti5vgf+pmxVE9fyqlL8/jVW4kYeoL0QMnL83svZc5wEq/EF0b3HfOl/dXsKY69KGTsnhkTKtw4k=
        on:
          all_branches: true
    - <<: *deploy_job
      name: >-
        Publishing on every commit
      if: >-
        branch == "master" AND
        type == "push"
      deploy:
        <<: *deploy_step
        server: https://test.pypi.org/legacy/
